#!/bin/sh

DOCKER_TOKEN=$1
DOCKER_IMAGE_TAG=$2
EXTRACT_TAG_FROM_GIT_REF=$3
DOCKERFILE=$4
BUILD_CONTEXT=$5
CUSTOM_DOCKER_BUILD_ARGS=$6

if [ $EXTRACT_TAG_FROM_GIT_REF == "true" ]; then
  DOCKER_IMAGE_TAG=$(git rev-parse --short HEAD)
fi

DOCKER_IMAGE_NAME=$(echo ghcr.io/${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')
DOCKER_IMAGE_NAME_WITH_TAG=$(echo ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} | tr '[:upper:]' '[:lower:]')

docker login -u publisher -p ${DOCKER_TOKEN} ghcr.io

docker build -t $DOCKER_IMAGE_NAME_WITH_TAG -f $DOCKERFILE $CUSTOM_DOCKER_BUILD_ARGS $BUILD_CONTEXT
docker push $DOCKER_IMAGE_NAME_WITH_TAG
